### ISSUE TITLE
希望支持LyCORIS的相关模型训练方法

### ISSUE THREAD

**Issue by sdbds** [IrisRainbowNeko/HCP-Diffusion#2]
项目链接在这里
https://github.com/KohakuBlueleaf/LyCORIS

LyCORIS是一个基于LoRA训练的扩展项目，包括一些其他算法的基于lora的模型，包括卷积locon、哈达玛积loha以及最新的克罗内克积lokr.
另外还有一个类似Ti的文本层模型，IA3

**Comment by KohakuBlueleaf** [comment]
@7eu7d7 我看了一下很喜歡你的trainer
打算搞一套支援
不知道有沒有辦法讓config file可以指定外部package的plugin network?

**Comment by 7eu7d7** [comment]
卷积本身就支持的，loha和lokr等会于近期支持

**Comment by IrisRainbowNeko** [comment]
已经由@KohakuBlueleaf 提供支持 https://github.com/KohakuBlueleaf/LyCORIS/tree/main/example_configs/training_configs/hcp
