### ISSUE TITLE
Tutorial Section links from Readme are not linking to the correct pages

### ISSUE THREAD

**Issue by wikidude** [IrisRainbowNeko/HCP-Diffusion#51]
When trying to access the links found in https://github.com/7eu7d7/HCP-Diffusion#tutorials the links turn up a 404 error as they have been moved around into /en/ and /zh_cn/ folders.
The links in the Tutorial section should be updated to the following for the English language:
```
[Model Training Tutorial](https://github.com/7eu7d7/HCP-Diffusion/blob/main/doc/guide_train.md) -> [Model Training Tutorial](https://github.com/7eu7d7/HCP-Diffusion/blob/main/doc/en/user_guides/train.md)
[DreamArtist++ Tutorial](https://github.com/7eu7d7/HCP-Diffusion/blob/main/doc/guide_DA.md) -> [DreamArtist++ Tutorial](https://github.com/7eu7d7/HCP-Diffusion/blob/main/doc/en/tutorial/DA.md)
[Model Inference Tutorial](https://github.com/7eu7d7/HCP-Diffusion/blob/main/doc/guide_infer.md) -> [Model Inference Tutorial](https://github.com/7eu7d7/HCP-Diffusion/blob/main/doc/en/user_guides/infer.md)
[Configuration File Explanation](https://github.com/7eu7d7/HCP-Diffusion/blob/main/doc/guide_cfg.md) -> [Configuration File Explanation](https://github.com/7eu7d7/HCP-Diffusion/blob/main/doc/en/user_guides/cfg.md)
[webui Model Conversion Tutorial](https://github.com/7eu7d7/HCP-Diffusion/blob/main/doc/guide_webui_lora.md) -> [webui Model Conversion Tutorial](https://github.com/7eu7d7/HCP-Diffusion/blob/main/doc/en/user_guides/model_convert.md)
```
Unfortunately I do not speak Chinese and cannot make recommendations for that.

Posting the updated links here without code brackets for temporary use by viewers of this issue until the update is made:

- [Model Training Tutorial](https://github.com/7eu7d7/HCP-Diffusion/blob/main/doc/en/user_guides/train.md)
- [DreamArtist++ Tutorial](https://github.com/7eu7d7/HCP-Diffusion/blob/main/doc/en/tutorial/DA.md)
- [Model Inference Tutorial](https://github.com/7eu7d7/HCP-Diffusion/blob/main/doc/en/user_guides/infer.md)
- [Configuration File Explanation](https://github.com/7eu7d7/HCP-Diffusion/blob/main/doc/en/user_guides/cfg.md)
- [webui Model Conversion Tutorial](https://github.com/7eu7d7/HCP-Diffusion/blob/main/doc/en/user_guides/model_convert.md)

With this out of the way, I can't wait to test your scripts. Hopefully they work on AMD.

**Comment by IrisRainbowNeko** [comment]
I forgot to update the doc link. docs has now been migrated to the [new link](https://hcpdiff.readthedocs.io/en/latest/)
