### ISSUE TITLE
Does this work well for SDXL training?

### ISSUE THREAD

**Issue by DarkAlchy** [IrisRainbowNeko/HCP-Diffusion#61]
I can't tell if it does or doesn't since I need to go back to university just to be able to use it from what I am seeing.  Hardest SD based tool I have yet to attempt to try AND it has no real help on it.  No vids, no guides, and nothing to help a new user to your tool, just a blinding white wiki documentation page that holds no real value of helping.

![image](https://github.com/IrisRainbowNeko/HCP-Diffusion/assets/10561690/27b0c590-e122-4b1a-9c00-0d95d70cb772)
Even the tutorial section are all 404 errors.

I searched the Internet and came up empty-handed for any info, regardless of which version, for help on your tool.,

Who uses this tool, and does it work well for SDXL training types?

**Comment by Deathawaits4** [comment]
Ive tried to use it, but i have yet to find out how to even do inference.. It doesnt even give you a tutorial on how to generate images with it. I managed to install it on runpod.. but then, well no idea what to do with it. Tried lora training as per guide, threw some errors without debug code. Just a "module not found error". It may be a powerfull tool, but if no one knows how to use it, it doesnt do anything.

**Comment by DarkAlchy** [comment]
> Ive tried to use it, but i have yet to find out how to even do inference.. It doesnt even give you a tutorial on how to generate images with it. I managed to install it on runpod.. but then, well no idea what to do with it. Tried lora training as per guide, threw some errors without debug code. Just a "module not found error". It may be a powerfull tool, but if no one knows how to use it, it doesnt do anything.
> 
> note i managed to do lora training on HCP before, but now its not working anymore at all.

I gave up and moved on.  So much potential, and power, in this tool but a lot of the people I talked to felt this dev might have been hired (due this work alone) somewhere and this is just a dead project, or, at the very most, a side project they touch once in a while.

**Comment by Iris-Neko** [comment]
already supported it

**Comment by DarkAlchy** [comment]
With as bad as the documentation is for this, and no videos or anything else out there and so much in a foreign language if I do find something with all the 404 where the documentation was supposed to be I just moved on with life.

Thanks.
